# Generated by Django 5.0.6 on 2024-06-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0002_alter_reserva_created_alter_reserva_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensiones',
            options={'verbose_name': 'Hora Disponible', 'verbose_name_plural': 'Horas Disponibles'},
        ),
    ]
